Introduce square gallery view, start with granularizing state management

diff --git a/experimental/examples/imageviewer/gradlew b/experimental/examples/imageviewer/gradlew
--- a/experimental/examples/imageviewer/gradlew
+++ b/experimental/examples/imageviewer/gradlew
@@ -55,7 +55,7 @@
 #       Darwin, MinGW, and NonStop.
 #
 #   (3) This script is generated from the Groovy template
-#       https://github.com/gradle/gradle/blob/master/subprojects/plugins/src/main/resources/org/gradle/api/internal/plugins/unixStartScript.txt
+#       https://github.com/gradle/gradle/blob/HEAD/subprojects/plugins/src/main/resources/org/gradle/api/internal/plugins/unixStartScript.txt
 #       within the Gradle project.
 #
 #       You can find Gradle at https://github.com/gradle/gradle/.
@@ -73,27 +73,35 @@ while
     [ -h "$app_path" ]
 do
     ls=$( ls -ld "$app_path" )
-    link=${ls#*' -> '}
-    case $link in             #(
-      /*)   app_path=$link ;; #(
-      *)    app_path=$APP_HOME$link ;;
-    esac
+link = ${ls#
+*' -> '}
+case
+$link in
+#(
+/*)   app_path=$link ;; #(
+*)    app_path=$APP_HOME$link ;;
+esac
 done
 
-APP_HOME=$( cd "${APP_HOME:-./}" && pwd -P ) || exit
-
-APP_NAME="Gradle"
+# This is normally unused
+# shellcheck disable=SC2034
 APP_BASE_NAME=${0##*/}
+APP_HOME = $(cd
+"${APP_HOME:-./}" && pwd -P ) ||
+exit
 
 # Add default JVM options here. You can also use JAVA_OPTS and GRADLE_OPTS to pass JVM options to this script.
-DEFAULT_JVM_OPTS='"-Xmx64m" "-Xms64m"'
+        DEFAULT_JVM_OPTS = '"-Xmx64m" "-Xms64m"'
 
 # Use the maximum available, or set MAX_FD != -1 to use that value.
-MAX_FD=maximum
+MAX_FD = maximum
 
-warn () {
-    echo "$*"
-} >&2
+warn() {
+    echo
+    "$*"
+}
+
+>&2
 
 die () {
     echo
@@ -133,32 +141,59 @@ location of your Java installation."
     fi
 else
     JAVACMD=java
-    which java >/dev/null 2>&1 || die "ERROR: JAVA_HOME is not set and no 'java' command could be found in your PATH.
+which java
+>/dev/null 2>&1 || die "ERROR: JAVA_HOME is not set and no 'java' command could be found in your PATH.
 
-Please set the JAVA_HOME variable in your environment to match the
-location of your Java installation."
+Please set
+the JAVA_HOME
+variable in
+your environment
+to match
+the
+        location
+of your
+Java installation
+."
 fi
 
 # Increase the maximum file descriptors if we can.
-if ! "$cygwin" && ! "$darwin" && ! "$nonstop" ; then
-    case $MAX_FD in #(
-      max*)
-        MAX_FD=$( ulimit -H -n ) ||
-            warn "Could not query maximum file descriptor limit"
-    esac
-    case $MAX_FD in  #(
-      '' | soft) :;; #(
-      *)
-        ulimit -n "$MAX_FD" ||
-            warn "Could not set maximum file descriptor limit to $MAX_FD"
-    esac
-fi
+if ! "$cygwin" && ! "$darwin" && ! "$nonstop"; then
+case
+$MAX_FD in
+#(
+max*)
+# In POSIX sh, ulimit -H is undefined. That's why the result is checked to see if it worked.
+# shellcheck disable=SC3045
+MAX_FD = $(ulimit - H - n) ||
+         warn
+"Could not query maximum file descriptor limit"
+esac
+case
+$MAX_FD in
+#(
+'' | soft) :;; #(
+*)
+# In POSIX sh, ulimit -n is undefined. That's why the result is checked to see if it worked.
+# shellcheck disable=SC3045
+ulimit -n "$MAX_FD" ||
+warn "Could not set maximum file descriptor limit to $MAX_FD"
+esac
+        fi
 
 # Collect all arguments for the java command, stacking in reverse order:
-#   * args from the command line
-#   * the main class name
+#   *
+args from
+the command
+line
+#   *
+the main
+
+class name
+
 #   * -classpath
-#   * -D...appname settings
+#   * -
+D...appname
+settings
 #   * --module-path (only if needed)
 #   * DEFAULT_JVM_OPTS, JAVA_OPTS, and GRADLE_OPTS environment variables.
 
