Regenerate gradle wrapper after Android Studio autoformatting debacle

diff --git a/experimental/examples/imageviewer/gradlew b/experimental/examples/imageviewer/gradlew
--- a/experimental/examples/imageviewer/gradlew
+++ b/experimental/examples/imageviewer/gradlew
@@ -73,35 +73,27 @@ while
     [ -h "$app_path" ]
 do
     ls=$( ls -ld "$app_path" )
-link = ${ls#
-*' -> '}
-case
-$link in
-#(
-/*)   app_path=$link ;; #(
-*)    app_path=$APP_HOME$link ;;
-esac
+    link=${ls#*' -> '}
+    case $link in             #(
+      /*)   app_path=$link ;; #(
+      *)    app_path=$APP_HOME$link ;;
+    esac
 done
 
 # This is normally unused
 # shellcheck disable=SC2034
 APP_BASE_NAME=${0##*/}
-APP_HOME = $(cd
-"${APP_HOME:-./}" && pwd -P ) ||
-exit
+APP_HOME=$( cd "${APP_HOME:-./}" && pwd -P ) || exit
 
 # Add default JVM options here. You can also use JAVA_OPTS and GRADLE_OPTS to pass JVM options to this script.
-        DEFAULT_JVM_OPTS = '"-Xmx64m" "-Xms64m"'
+DEFAULT_JVM_OPTS='"-Xmx64m" "-Xms64m"'
 
 # Use the maximum available, or set MAX_FD != -1 to use that value.
-MAX_FD = maximum
+MAX_FD=maximum
 
-warn() {
-    echo
-    "$*"
-}
-
->&2
+warn () {
+    echo "$*"
+} >&2
 
 die () {
     echo
@@ -112,29 +104,25 @@ die () {
 
 # OS specific support (must be 'true' or 'false').
 cygwin=false
-msys = false
-darwin = false
-nonstop = false
+msys=false
+darwin=false
+nonstop=false
 case "$( uname )" in                #(
-CYGWIN* )
-cygwin = true;; #(
-Darwin* )
-darwin = true;; #(
-MSYS* | MINGW* )
-msys = true;; #(
+  CYGWIN* )         cygwin=true  ;; #(
+  Darwin* )         darwin=true  ;; #(
+  MSYS* | MINGW* )  msys=true    ;; #(
   NONSTOP* )        nonstop=true ;;
 esac
 
-        CLASSPATH = $APP_HOME / gradle / wrapper / gradle - wrapper.jar
+CLASSPATH=$APP_HOME/gradle/wrapper/gradle-wrapper.jar
 
 
 # Determine the Java command to use to start the JVM.
-if [ -n "$JAVA_HOME" ]; then
-if [ -x "$JAVA_HOME/jre/sh/java" ];
-then
-# IBM's JDK on AIX uses strange locations for the executables
-        JAVACMD = $JAVA_HOME / jre / sh / java
-else
+if [ -n "$JAVA_HOME" ] ; then
+    if [ -x "$JAVA_HOME/jre/sh/java" ] ; then
+        # IBM's JDK on AIX uses strange locations for the executables
+        JAVACMD=$JAVA_HOME/jre/sh/java
+    else
         JAVACMD=$JAVA_HOME/bin/java
     fi
     if [ ! -x "$JAVACMD" ] ; then
@@ -145,59 +133,36 @@ location of your Java installation."
     fi
 else
     JAVACMD=java
-which java
->/dev/null 2>&1 || die "ERROR: JAVA_HOME is not set and no 'java' command could be found in your PATH.
+    which java >/dev/null 2>&1 || die "ERROR: JAVA_HOME is not set and no 'java' command could be found in your PATH.
 
-Please set
-the JAVA_HOME
-variable in
-your environment
-to match
-the
-        location
-of your
-Java installation
-."
+Please set the JAVA_HOME variable in your environment to match the
+location of your Java installation."
 fi
 
 # Increase the maximum file descriptors if we can.
-if ! "$cygwin" && ! "$darwin" && ! "$nonstop"; then
-case
-$MAX_FD in
-#(
-max*)
-# In POSIX sh, ulimit -H is undefined. That's why the result is checked to see if it worked.
-# shellcheck disable=SC3045
-MAX_FD = $(ulimit - H - n) ||
-         warn
-"Could not query maximum file descriptor limit"
-esac
-case
-$MAX_FD in
-#(
-'' | soft) :;; #(
-*)
-# In POSIX sh, ulimit -n is undefined. That's why the result is checked to see if it worked.
-# shellcheck disable=SC3045
-ulimit -n "$MAX_FD" ||
-warn "Could not set maximum file descriptor limit to $MAX_FD"
-esac
-        fi
+if ! "$cygwin" && ! "$darwin" && ! "$nonstop" ; then
+    case $MAX_FD in #(
+      max*)
+        # In POSIX sh, ulimit -H is undefined. That's why the result is checked to see if it worked.
+        # shellcheck disable=SC3045 
+        MAX_FD=$( ulimit -H -n ) ||
+            warn "Could not query maximum file descriptor limit"
+    esac
+    case $MAX_FD in  #(
+      '' | soft) :;; #(
+      *)
+        # In POSIX sh, ulimit -n is undefined. That's why the result is checked to see if it worked.
+        # shellcheck disable=SC3045 
+        ulimit -n "$MAX_FD" ||
+            warn "Could not set maximum file descriptor limit to $MAX_FD"
+    esac
+fi
 
 # Collect all arguments for the java command, stacking in reverse order:
-#   *
-args from
-the command
-line
-#   *
-the main
-
-class name
-
+#   * args from the command line
+#   * the main class name
 #   * -classpath
-#   * -
-D...appname
-settings
+#   * -D...appname settings
 #   * --module-path (only if needed)
 #   * DEFAULT_JVM_OPTS, JAVA_OPTS, and GRADLE_OPTS environment variables.
 
@@ -208,19 +173,12 @@ if "$cygwin" || "$msys" ; then
 
     JAVACMD=$( cygpath --unix "$JAVACMD" )
 
-# Now convert the arguments - kludge to limit ourselves to /bin/sh
-for arg do
-if
-case
-$arg in
-#(
--*)   false;;                            # don't mess with options #(
-/?*)
-t = ${arg#
-/}
-t =
-/${
-t%%/*}              # looks like a POSIX filepath
+    # Now convert the arguments - kludge to limit ourselves to /bin/sh
+    for arg do
+        if
+            case $arg in                                #(
+              -*)   false ;;                            # don't mess with options #(
+              /?*)  t=${arg#/} t=/${t%%/*}              # looks like a POSIX filepath
                     [ -e "$t" ] ;;                      #(
               *)    false ;;
             esac
