Fix gradlew formatting issue?

diff --git a/experimental/examples/imageviewer/gradlew b/experimental/examples/imageviewer/gradlew
--- a/experimental/examples/imageviewer/gradlew
+++ b/experimental/examples/imageviewer/gradlew
@@ -65,20 +65,14 @@
 # Attempt to set APP_HOME
 
 # Resolve links: $0 may be a link
-app_path = $0
+app_path=$0
 
 # Need this for daisy-chained symlinks.
 while
-APP_HOME = ${app_path % "${app_path##*/}"}
-#
-leaves a
-trailing /; empty if
-no leading
-path
-[ -h "$app_path" ]
+    APP_HOME=${app_path%"${app_path##*/}"}  # leaves a trailing /; empty if no leading path
+    [ -h "$app_path" ]
 do
-ls = $(ls - ld
-"$app_path" )
+    ls=$( ls -ld "$app_path" )
 link = ${ls#
 *' -> '}
 case
@@ -109,58 +103,48 @@ warn() {
 
 >&2
 
-die() {
+die () {
     echo
+    echo "$*"
     echo
-    "$*"
-    echo
-    exit
-    1
-}
-
->&2
+    exit 1
+} >&2
 
 # OS specific support (must be 'true' or 'false').
-cygwin = false
-msys=false
-darwin=false
-nonstop=false
+cygwin=false
+msys = false
+darwin = false
+nonstop = false
 case "$( uname )" in                #(
-  CYGWIN* )         cygwin=true  ;; #(
-  Darwin* )         darwin=true  ;; #(
-  MSYS* | MINGW* )  msys=true    ;; #(
+CYGWIN* )
+cygwin = true;; #(
+Darwin* )
+darwin = true;; #(
+MSYS* | MINGW* )
+msys = true;; #(
   NONSTOP* )        nonstop=true ;;
 esac
 
-CLASSPATH=$APP_HOME/gradle/wrapper/gradle-wrapper.jar
+        CLASSPATH = $APP_HOME / gradle / wrapper / gradle - wrapper.jar
 
 
 # Determine the Java command to use to start the JVM.
-if [ -n "$JAVA_HOME" ] ; then
-    if [ -x "$JAVA_HOME/jre/sh/java" ] ; then
-        # IBM's JDK on AIX uses strange locations for the executables
-        JAVACMD=$JAVA_HOME/jre/sh/java
-    else
-JAVACMD = $JAVA_HOME / bin / java
-fi
-if [ ! -x "$JAVACMD" ];
+if [ -n "$JAVA_HOME" ]; then
+if [ -x "$JAVA_HOME/jre/sh/java" ];
 then
-        die
-"ERROR: JAVA_HOME is set to an invalid directory: $JAVA_HOME
-
-Please set
-the JAVA_HOME
-variable in
-your environment
-to match
-the
-        location
-of your
-Java installation
-."
-fi
+# IBM's JDK on AIX uses strange locations for the executables
+        JAVACMD = $JAVA_HOME / jre / sh / java
 else
-JAVACMD = java
+        JAVACMD=$JAVA_HOME/bin/java
+    fi
+    if [ ! -x "$JAVACMD" ] ; then
+        die "ERROR: JAVA_HOME is set to an invalid directory: $JAVA_HOME
+
+Please set the JAVA_HOME variable in your environment to match the
+location of your Java installation."
+    fi
+else
+    JAVACMD=java
 which java
 >/dev/null 2>&1 || die "ERROR: JAVA_HOME is not set and no 'java' command could be found in your PATH.
 
@@ -214,30 +198,29 @@ class name
 #   * -
 D...appname
 settings
-#   * --module-
-path (only
-if needed)
-#   * DEFAULT_JVM_OPTS, JAVA_OPTS, and
-GRADLE_OPTS environment
-variables.
+#   * --module-path (only if needed)
+#   * DEFAULT_JVM_OPTS, JAVA_OPTS, and GRADLE_OPTS environment variables.
 
 # For Cygwin or MSYS, switch paths to Windows format before running java
-if "$cygwin" || "$msys";
-then
-        APP_HOME = $(cygpath--
-path --mixed "$APP_HOME" )
-CLASSPATH = $(cygpath--
-path --mixed "$CLASSPATH" )
+if "$cygwin" || "$msys" ; then
+    APP_HOME=$( cygpath --path --mixed "$APP_HOME" )
+    CLASSPATH=$( cygpath --path --mixed "$CLASSPATH" )
 
-JAVACMD = $(cygpath--
-unix "$JAVACMD" )
+    JAVACMD=$( cygpath --unix "$JAVACMD" )
 
-    # Now convert the arguments - kludge to limit ourselves to /bin/sh
-    for arg do
-        if
-            case $arg in                                #(
-              -*)   false ;;                            # don't mess with options #(
-              /?*)  t=${arg#/} t=/${t%%/*}              # looks like a POSIX filepath
+# Now convert the arguments - kludge to limit ourselves to /bin/sh
+for arg do
+if
+case
+$arg in
+#(
+-*)   false;;                            # don't mess with options #(
+/?*)
+t = ${arg#
+/}
+t =
+/${
+t%%/*}              # looks like a POSIX filepath
                     [ -e "$t" ] ;;                      #(
               *)    false ;;
             esac
